global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:5001']  # Assuming that your ASP.NET Core app is exposing metrics on port 5001.
  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']  # Assuming that your ASP.NET Core API is exposing metrics on port 5000.
